### ISSUE TITLE
💄 [UI] Tag 컴포넌트 제작

### ISSUE THREAD

**Issue by ghdtjgus76** [Team-TIFY/TIFY-CLIENT#14]
# ✨ 어떤 작업인가요?
Tag 컴포넌트를 제작합니다.

# ☑ TODO
- [x]  Tag 컴포넌트 제작 (Icon 없이)
- [x]  스토리북 작성
- [x] Icon 추가

**Comment by eugene028** [comment]
아이콘 없이 일단 만들어줘 서현!!
내가 추가할게 아이콘은 나중에 .. 아직 아이콘 컴폰넌트 만들기 전이라서

**Comment by ghdtjgus76** [comment]
알겠어~!
